---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvd-agent
  labels:
    app: alvd-agent
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alvd-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alvd-agent
        app.kubernetes.io/name: alvd
        app.kubernetes.io/component: agent
    spec:
      initContainers:
      containers:
        - name: alvd-agent
          image: "rinx/alvd:noavx"
          imagePullPolicy: Always
          args:
            - agent
            - --name=$(MY_POD_NAME)
            - --server=alvd-server.$(MY_POD_NAMESPACE).svc.cluster.local:8000
            - --log-level=info
            - --dimension=784
            - --distance-type=l2
            - --object-type=float
          ports:
            - name: agent-grpc
              protocol: TCP
              containerPort: 8081
            - name: prometheus
              protocol: TCP
              containerPort: 9090
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 250Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: alvd-agent
  labels:
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: agent
spec:
  ports:
    - name: agent-grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: agent
  clusterIP: None
  type: ClusterIP
