---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvd-server
  labels:
    app: alvd-server
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alvd-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alvd-server
        app.kubernetes.io/name: alvd
        app.kubernetes.io/component: server
    spec:
      initContainers:
      containers:
        - name: alvd-server
          image: "rinx/alvd:noavx"
          imagePullPolicy: Always
          args:
            - server
            - --agent=false
            - --log-level=info
            - --replicas=2
            - --check-index-interval=5s
            - --create-index-threshold=1
          ports:
            - name: server
              protocol: TCP
              containerPort: 8000
            - name: grpc
              protocol: TCP
              containerPort: 8080
            - name: agent-grpc
              protocol: TCP
              containerPort: 8081
            - name: prometheus
              protocol: TCP
              containerPort: 9090
          resources:
            limits:
              cpu: 750m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: alvd-server
  labels:
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: server
spec:
  ports:
    - name: server
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: agent-grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: alvd
    app.kubernetes.io/component: server
  clusterIP: None
  type: ClusterIP
