global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: alvd-services
    static_configs:
      - targets:
        - "alvd-server:9090"
        - "alvd-agent-1:9090"
        - "alvd-agent-2:9090"
        - "alvd-agent-3:9090"
  - job_name: prometheus
    static_configs:
      - targets:
        - "prometheus:9090"
