name: "Build"
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "*.*.*-*"
      - "v*.*.*-*"
    paths:
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"
      - "Makefile"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"
      - "Makefile"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Build
        run: |
          sudo make ngt/install
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: alvd-linux
          path: cmd/alvd/alvd
  build-linux-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Build
        run: |
          sudo make NGT_BUILD_OPTIONS='' ngt/install
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: alvd-linux-avx2
          path: cmd/alvd/alvd
