name: "Build"
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "*.*.*-*"
      - "v*.*.*-*"
    paths:
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"
      - "Makefile"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"
      - "Makefile"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Build
        run: |
          sudo make ngt/install
          make
      - name: Zip
        run: |
          zip --junk-paths alvd-linux-amd64.zip cmd/alvd/alvd
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: alvd-linux-amd64.zip
          path: ./alvd-linux-amd64.zip
  build-linux-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Build
        run: |
          sudo make NGT_BUILD_OPTIONS='' ngt/install
          make
      - name: Zip
        run: |
          zip --junk-paths alvd-linux-amd64-avx2.zip cmd/alvd/alvd
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: alvd-linux-amd64-avx2.zip
          path: ./alvd-linux-amd64-avx2.zip
  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-linux-avx2
    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v1
        with:
          name: alvd-linux-amd64.zip
          path: tmp
      - name: Upload Release Asset (linux)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/alvd-linux-amd64.zip
          asset_name: alvd-linux-amd64.zip
          asset_content_type: application/zip
      - uses: actions/download-artifact@v1
        with:
          name: alvd-linux-amd64-avx2.zip
          path: tmp
      - name: Upload Release Asset (linux-static)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/alvd-linux-amd64-avx2.zip
          asset_name: alvd-linux-amd64-avx2.zip
          asset_content_type: application/zip
