name: "Build Docker image"
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "*.*.*-*"
      - "v*.*.*-*"
    paths:
      - ".github/workflows/docker.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"
      - "Makefile"

jobs:
  build-noavx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-alvd-noavx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-alvd-noavx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_USER }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - name: extra tags
        if: startsWith( github.ref, 'refs/tags/')
        run: |
          tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
          primary_name=`make docker/build/noavx/name`
          secondary_name=`make docker/build/noavx/altname`
          EXTRA_OPTS="-t ${primary_name}-${tag_name} -t ${secondary_name}-${tag_name}"
          echo "EXTRA_OPTS=${EXTRA_OPTS}" >> $GITHUB_ENV
      - name: Build
        run: |
          make \
            DOCKER="docker buildx" \
            DOCKER_OPTS="--platform ${PLATFORMS} --builder ${BUILDER} ${CACHE_OPTS} ${LABEL_OPTS} ${EXTRA_OPTS} --push" \
            docker/build/noavx
        env:
          DOCKER_BUILDKIT: 1
          PLATFORMS: ${{ steps.qemu.outputs.platforms }}
          BUILDER: ${{ steps.buildx.outputs.name }}
          CACHE_OPTS: "--cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache"
          LABEL_OPTS: "--label org.opencontainers.image.url=${{ github.event.repository.html_url }} --label org.opencontainers.image.source=${{ github.event.repository.html_url }} --label org.opencontainers.image.revision=${{ github.sha }}"
  build-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-alvd-avx2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-alvd-avx2-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_USER }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - name: extra tags
        if: startsWith( github.ref, 'refs/tags/')
        run: |
          tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
          primary_name=`make docker/build/avx2/name`
          secondary_name=`make docker/build/avx2/altname`
          EXTRA_OPTS="-t ${primary_name}-${tag_name} -t ${secondary_name}-${tag_name}"
          echo "EXTRA_OPTS=${EXTRA_OPTS}" >> $GITHUB_ENV
      - name: Build
        run: |
          make \
            DOCKER="docker buildx" \
            DOCKER_OPTS="--builder ${BUILDER} ${CACHE_OPTS} ${LABEL_OPTS} ${EXTRA_OPTS} --push" \
            docker/build/avx2
        env:
          DOCKER_BUILDKIT: 1
          BUILDER: ${{ steps.buildx.outputs.name }}
          CACHE_OPTS: "--cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache"
          LABEL_OPTS: "--label org.opencontainers.image.url=${{ github.event.repository.html_url }} --label org.opencontainers.image.source=${{ github.event.repository.html_url }} --label org.opencontainers.image.revision=${{ github.sha }}"
